### PR TITLE
Update to 0.11

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by martindurant** [comment]
Source URL should be https://pypi.io/packages/source/t/thrift/thrift-0.11.0.tar.gz (not .zip) ?

**Comment by martindurant** [comment]
Seems to still think it's a .zip file
```
Downloading source to cache: thrift-0.11.0.zip
Downloading https://pypi.io/packages/source/t/thrift/thrift-0.11.0.tar.gz
```

**Comment by melund** [comment]
@martindurant Sorry. I only changed the URL. My fault.

**Comment by mariusvniekerk** [comment]
@melund anyone can do it.  There are some other bot commands it will do as well

**Comment by martindurant** [comment]
pleas merge

**Comment by melund** [comment]
Thanks a lot @mariusvniekerk

**Pull request merged**
